# .readthedocs.yaml
# ReadTheDocs configuration
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install -e "../.[dev]" || true  # install project for mkdocstrings

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements-docs.txt
